name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    runs-on: docker-web-runners
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: container-registry.k8s.home.blrobinson.uk/docker-web:latest
      - uses: azure/setup-kubectl@v3
      - name: Start Rollout restart
        run: kubectl rollout restart deployment/web -n ingress
      - name: Monitor restart
        run: kubectl rollout status deployment/web -n ingress