name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-docker-build.yaml@master
    with:
      runners: docker-web-runners
      image: docker-web
  deploy:
    runs-on: docker-web-runners
    needs: docker-build-push
    steps:
      - name: Get git shortsha
        id: vars
        run: ::set-output name=short_sha::$(git rev-parse --short=12 ${{ github.sha }})
      - name: Setup Git
        uses: actions4git/setup-git@v1
      - name: Checkout Flux Repo
        uses: actions/checkout@v4
        with:
          repository: bl-robinson/home-flux
          path: flux
      - name: Update Image Ref
        working-directory: ./flux
        run: sed -i -e 's/\(container-registry.k8s.home.blrobinson.uk\/docker-web\):\(.*\)/\1:sha-${{ steps.vars.outputs.short_sha }}/g' clusters/home/web-ingress/nginx.yaml
      - name: Commit change
        working-directory: ./flux
        run: 'git commit clusters/home/web-ingress/nginx.yaml -m "deploy: Deploying version sha-${{ steps.vars.outputs.short_sha }}"'
      - name: Push Commit
        working-directory: ./flux
        run: git push
      # - uses: azure/setup-kubectl@v3
      # - name: Start Rollout restart
      #   run: kubectl rollout restart deployment/web -n ingress
      # - name: Monitor restart
      #   run: kubectl rollout status deployment/web -n ingress