name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-docker-build.yaml@master
    with:
      runners: docker-web-runners
      image: docker-web
  deploy:
    runs-on: docker-web-runners
    needs: docker-build-push
    steps:
      - uses: azure/setup-kubectl@v3
      - name: Start Rollout restart
        run: kubectl rollout restart deployment/web -n ingress
      - name: Monitor restart
        run: kubectl rollout status deployment/web -n ingress