name: Build Push Image

on:
  workflow_dispatch:

jobs:
  docker-build-push:
    runs-on: docker-web-runners
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: container-registry.k8s.home.blrobinson.uk/docker-web:latest
