name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-docker-build.yaml@master
    with:
      runners: docker-web-runners
      image: docker-web
  deploy:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-flux-deploy.yaml@master
    secrets: inherit
    needs: docker-build-push
    with:
      runners: docker-web-runners
      old-image: container-registry.k8s.home.blrobinson.uk/docker-web
      deploy-image: ${{ needs.docker-build-push.outputs.tags }}
      namespace: ingress
      deployment-name: web
      kustomization: web-ingress
      flux-file: clusters/home/web-ingress/nginx.yaml
  revert:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-flux-deploy.yaml@master
    if: ${{ always() && needs.deploy.result == 'failure' }}
    secrets: inherit
    needs: deploy
    with:
      runners: docker-web-runners
      revert: true
      revert-sha: ${{ needs.deploy.outputs.deploy-sha }}
