name: Build Push Image

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  docker-build-push:
    uses: bl-robinson/gha-shared-workflows/.github/workflows/re-usable-docker-build.yaml@master
    with:
      runners: docker-web-runners
      image: docker-web
  deploy:
    runs-on: docker-web-runners
    needs: docker-build-push
    steps:
      - name: Checkout Flux Repo
        uses: actions/checkout@v4
        with:
          repository: bl-robinson/home-flux
          path: flux
      - name: Update Image Ref
        run: sed -i -e 's_container-registry.k8s.home.blrobinson.uk/docker-web:.*_${{ needs.docker-build-push.outputs.tags }}_g' clusters/home/web-ingress/nginx.yaml
        working-directory: ./flux
      - name: Unset existing github auth
        # This step is needed as GHA auto sets some config which the setup-git action below does not clear. Need to raise an issue there.
        run: git config --unset-all http.https://github.com/.extraheader
        working-directory: ./flux
      - name: Setup Git
        uses: actions4git/setup-git@v1
        with:
          github-token: ${{ secrets.PUSH_TOKEN }}
          safe-directory: ./flux
      - name: Commit change
        working-directory: ./flux
        run: 'git commit clusters/home/web-ingress/nginx.yaml -m "deploy: Deploying version ${{ steps.container-sha.outputs.CONTAINER_SHORT_SHA }}"'
      - name: Get Flux Sha
        id: flux-sha
        working-directory: ./flux
        run: echo "FLUX_SHA=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
      - name: Push Commit
        working-directory: ./flux
        run: git push
      - uses: azure/setup-kubectl@v3
      - name: Wait for Reconcile
        # I don't really like this line... but it'll do the job... (probably)
        run: timeout 60s sh -c "until kubectl get ks -n flux-system web-ingress -o json | jq '.status.conditions[0].message' | grep 'Applied revision:' | grep '${{ steps.flux-sha.outputs.FLUX_SHA }}'; do echo 'Waiting for Reconciliation...'; sleep 5; done"
